baseurl: ''
url: 'https://www.quedic.com'
permalink: pretty
title: 'Quedic'
description: 'Integrated PR, marketing & KOL for Web3 exchanges and protocols.'
og_image: '/images/og-image.png'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"

collections:
  services:
    output: true
    sort_by: weight
    permalink: /services/:path/
  services_zh:
    output: true
    sort_by: weight
    permalink: /zh-tw/services/:path/
  services_ja:
    output: true
    sort_by: weight
    permalink: /ja/services/:path/
  industries:
    output: true
    sort_by: weight
    permalink: /industries/:path/
  industries_zh:
    output: true
    sort_by: weight
    permalink: /zh-tw/industries/:path/
  industries_ja:
    output: true
    sort_by: weight
    permalink: /ja/industries/:path/

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
      lang: "en"
  - scope:
      path: ""
      type: "services_zh"
    values:
      layout: "service-zh"
      lang: "zh-tw"
  - scope:
      path: ""
      type: "services_ja"
    values:
      layout: "service-ja"
      lang: "ja"
  - scope:
      path: ""
      type: "industries"
    values:
      layout: "industry"
      lang: "en"
  - scope:
      path: ""
      type: "industries_zh"
    values:
      layout: "industry-zh"
      lang: "zh-tw"
  - scope:
      path: ""
      type: "industries_ja"
    values:
      layout: "industry-ja"
      lang: "ja"

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - run.sh
